name: flight_weather
version: '1.0.0'
config-version: 2
profile: flight_weather
model-paths: [models]
seed-paths: [seeds]
clean-targets: [target, dbt_packages]
models:
  flight_weather:
    staging:
      +materialized: view
    marts:
      +materialized: table

